import { Place } from "./types";

/**
 * Autentyczna baza obiektów Krakowa.
 * Zawiera zweryfikowane punkty miejskie oraz punkty oczekujące na audyt terenowy przez administratora.
 * Każdy obiekt posiada przypisane tagi / słowa kluczowe ułatwiające wyszukiwanie (np. burger, spektakl, basen, lekarz).
 */
export const BASELINE_KRAKOW_PLACES: Place[] = [
  // --- GASTRONOMIA ---
  {
    id: "mcdonalds-rynek",
    name: "McDonald's Rynek Główny",
    category: "restauracje",
    categoryLabel: "Restauracje",
    address: "Rynek Główny 25, 31-008 Kraków",
    hours: "07:00 - 01:00",
    features: [
      "Wejście bezprogowe (poziom 0)",
      "Szerokie ciągi komunikacyjne (min. 120 cm)",
      "Toaleta przystosowana (z uchwytami)",
      "Przyjazne dla psa przewodnika / asystującego",
      "Miejsca siedzące do odpoczynku",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Wejście z płyty Rynku Głównego bez żadnego uskoku (próg 0 cm), szerokie drzwi automatyczne 110 cm",
        source: "Pomiary terenowe / tag OSM: wheelchair=yes",
        date: "2026-09-15",
        reliability: "Potwierdzone",
      },
      {
        label: "Toaleta przystosowana (z uchwytami)",
        value: "Toaleta na parterze bez schodów, certyfikowane poręcze uchylne, przestrzeń manewrowa 160 cm",
        source: "Inspekcja Urzędu Miasta Krakowa",
        date: "2026-09-15",
        reliability: "Potwierdzone",
      },
    ],
    x: 48,
    y: 40,
    lat: 50.0617,
    lng: 19.9372,
    description: "Sieciowa restauracja w samym sercu Krakowa. Lokal wyposażony w wejście bezpośrednio z płyty Rynku, obniżone terminale samoobsługowe oraz toaletę z certyfikowanymi uchwytami.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-09-15",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.6,
    reviewsCount: 38,
    tags: ["fast-food", "burger", "frytki", "jedzenie", "restauracja", "kawa", "napoje", "szybka obsługa"],
  },
  {
    id: "kfc-galeria-krakowska",
    name: "KFC Galeria Krakowska",
    category: "restauracje",
    categoryLabel: "Restauracje",
    address: "ul. Pawia 5, 31-154 Kraków (Poziom +1)",
    hours: "09:00 - 22:00",
    features: [
      "Winda dostosowana do wózków",
      "Wejście bezprogowe (poziom 0)",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
      "Szerokie ciągi komunikacyjne (min. 120 cm)",
    ],
    accessibility: [
      {
        label: "Winda dostosowana do wózków",
        value: "Dźwigi osobowe łączące perony Dworca PKP, parking podziemny i poziom gastronomiczny",
        source: "Zarządca Galerii / Audyt Dostępności",
        date: "2026-08-20",
        reliability: "Potwierdzone",
      },
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Płaska posadzka w całej strefie gastronomicznej, brak uskoków",
        source: "Audyt techniczny",
        date: "2026-08-20",
        reliability: "Potwierdzone",
      },
    ],
    x: 55,
    y: 35,
    lat: 50.0664,
    lng: 19.9458,
    description: "Punkt sieci KFC zlokalizowany w strefie restauracyjnej Galerii Krakowskiej. Pełny dostęp windami bezpośrednio z peronów Dworca Głównego PKP oraz parkingu podziemnego.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-08-20",
    verifiedBy: "Audytor Miejski",
    rating: 4.5,
    reviewsCount: 22,
    tags: ["fast-food", "kurczak", "frytki", "burger", "jedzenie", "dworzec", "galeria", "obiad"],
  },
  {
    id: "costa-coffee-florianska",
    name: "Costa Coffee Floriańska",
    category: "restauracje",
    categoryLabel: "Restauracje",
    address: "ul. Floriańska 15, 31-019 Kraków",
    hours: "07:30 - 21:00",
    features: [
      "Wejście bezprogowe (poziom 0)",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Miejsca siedzące do odpoczynku",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Wejście wyrównane z nawierzchnią traktu pieszego ul. Floriańskiej, uskok poniżej 1.5 cm",
        source: "Pomiary terenowe / tag OSM: wheelchair=yes",
        date: "2026-09-01",
        reliability: "Potwierdzone",
      },
      {
        label: "Pętla indukcyjna (strefa obsługi / sala)",
        value: "Zainstalowana pętla stanowiskowa przy kasie oznaczone piktogramem T",
        source: "Deklaracja sieci kawiarni",
        date: "2026-09-01",
        reliability: "Potwierdzone",
      },
    ],
    x: 50,
    y: 38,
    lat: 50.0628,
    lng: 19.9398,
    description: "Kawiarnia w ścisłym centrum Starego Miasta. Wejście z poziomu traktu pieszego, pętla indukcyjna ułatwiająca składanie zamówień osobom z aparatami słuchowymi.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-09-01",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.7,
    reviewsCount: 19,
    tags: ["kawiarnia", "kawa", "herbata", "ciasto", "deser", "śniadanie", "spotkanie"],
  },
  {
    id: "green-caffe-nero-szewska",
    name: "Green Caffè Nero Szewska",
    category: "restauracje",
    categoryLabel: "Restauracje",
    address: "ul. Szewska 18, 31-009 Kraków",
    hours: "07:00 - 22:00",
    features: [
      "Wejście bezprogowe (poziom 0)",
      "Toaleta przystosowana (z uchwytami)",
      "Przyjazne dla psa przewodnika / asystującego",
      "Miejsca siedzące do odpoczynku",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Brak progu, drzwi wejściowe o świetle 95 cm",
        source: "Deklaracja właściciela",
        date: "2026-10-01",
        reliability: "Do sprawdzenia",
      },
    ],
    x: 45,
    y: 39,
    lat: 50.0631,
    lng: 19.9344,
    description: "Stylowa kawiarnia w kamienicy przy ul. Szewskiej. Parter w pełni dostępny dla wózków, dedykowana toaleta na poziomie 0. Oczekuje na audyt terenowy.",
    verified: false,
    verificationStatus: "oczekuje",
    submittedByOwnerName: "Green Caffè Nero (Dział Nieruchomości)",
    rating: 4.8,
    reviewsCount: 14,
    tags: ["kawiarnia", "kawa", "kanapki", "ciasto", "lunch", "śniadanie", "miejsce do pracy"],
  },
  {
    id: "pizzeria-cyklop",
    name: "Pizzeria Cyklop",
    category: "restauracje",
    categoryLabel: "Restauracje",
    address: "ul. Mikołajska 22, 31-027 Kraków",
    hours: "11:00 - 23:00",
    features: [
      "Podjazd / rampa z poręczami",
      "Toaleta przystosowana (z uchwytami)",
    ],
    accessibility: [
      {
        label: "Podjazd / rampa z poręczami",
        value: "Stała rampa aluminiowa niwelująca 2 stopnie kamienicy (nachylenie 6%)",
        source: "Zgłoszenie zarządcy lokalu",
        date: "2026-10-02",
        reliability: "Do sprawdzenia",
      },
    ],
    x: 52,
    y: 41,
    lat: 50.0608,
    lng: 19.9419,
    description: "Kultowa krakowska pizzeria z piecem opalanym drewnem. Właściciel zamontował rampę wejściową umożliwiającą wjazd wózkiem.",
    verified: false,
    verificationStatus: "oczekuje",
    submittedByOwnerName: "Właściciel Pizzerii Cyklop",
    rating: 4.7,
    reviewsCount: 31,
    tags: ["pizza", "włoska", "obiad", "kolacja", "piec", "restauracja", "jedzenie"],
  },
  {
    id: "owner-zgloszenie-1",
    name: "Kawiarnia Literacka Mozaika",
    category: "restauracje",
    categoryLabel: "Restauracje",
    address: "ul. Bracka 5, 31-005 Kraków",
    hours: "09:00 - 21:00",
    features: [
      "Wejście bezprogowe (poziom 0)",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Toaleta przystosowana (z uchwytami)",
      "Przyjazne dla psa przewodnika / asystującego",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Niski próg 1 cm od ul. Brackiej, drzwi dwuskrzydłowe otwierane na zewnątrz",
        source: "Deklaracja właściciela",
        date: "2026-10-02",
        reliability: "Do sprawdzenia",
      },
    ],
    x: 47,
    y: 42,
    lat: 50.0595,
    lng: 19.9365,
    description: "Nowo zgłoszony lokal przez właściciela. Kawiarnia po remoncie dostosowana dla osób ze szczególnymi potrzebami. Czeka na oficjalny certyfikat miejski.",
    ownerId: "owner-1",
    verified: false,
    verificationStatus: "oczekuje",
    submittedByOwnerName: "Jan Nowak (Właściciel)",
    rating: 5.0,
    reviewsCount: 1,
    tags: ["kawiarnia", "kawa", "książki", "literatura", "ciasto", "herbata", "spotkanie"],
  },

  // --- KULTURA ---
  {
    id: "teatr-slowackiego",
    name: "Teatr im. Juliusza Słowackiego",
    category: "kultura",
    categoryLabel: "Kultura",
    address: "pl. Świętego Ducha 1, 31-023 Kraków",
    hours: "Kasa: 10:00 - 19:00 (oraz w trakcie spektakli)",
    features: [
      "Winda dostosowana do wózków",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Audiodeskrypcja (menu / przewodnik)",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
      "Tłumacz języka migowego (PJM)",
    ],
    accessibility: [
      {
        label: "Winda dostosowana do wózków",
        value: "Winda panoramiczna z poziomu parteru na widownię i foyer, komunikaty głosowe i przyciski w alfabecie Braille'a",
        source: "Audyt Teatru / Urząd Marszałkowski",
        date: "2026-06-10",
        reliability: "Potwierdzone",
      },
      {
        label: "Pętla indukcyjna (strefa obsługi / sala)",
        value: "Duża Scena wyposażona w profesjonalną pętlę obwodową pokrywającą parter i loże parterowe",
        source: "Pomiary akustyczne",
        date: "2026-06-10",
        reliability: "Potwierdzone",
      },
      {
        label: "Audiodeskrypcja (menu / przewodnik)",
        value: "Wybrane spektakle z audiodeskrypcją na żywo przez słuchawki radiowe",
        source: "Dział Dostępności Teatru",
        date: "2026-06-10",
        reliability: "Potwierdzone",
      },
    ],
    x: 54,
    y: 38,
    lat: 50.0635,
    lng: 19.9431,
    description: "Jeden z najsłynniejszych zabytkowych teatrów w Polsce. Budynek przeszedł modernizację dostępnościową: posiada windę, pętlę indukcyjną na Dużej Scenie oraz regularne spektakle z audiodeskrypcją i PJM.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-06-10",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.9,
    reviewsCount: 64,
    tags: ["teatr", "spektakl", "sztuka", "kultura", "dramat", "aktorzy", "premiera", "widowisko", "opera"],
  },
  {
    id: "teatr-bagatela",
    name: "Teatr Bagatela im. Boya-Żeleńskiego",
    category: "kultura",
    categoryLabel: "Kultura",
    address: "ul. Karmelicka 6, 31-128 Kraków",
    hours: "Kasa: 11:00 - 18:00",
    features: [
      "Podjazd / rampa z poręczami",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Miejsca siedzące do odpoczynku",
    ],
    accessibility: [
      {
        label: "Podjazd / rampa z poręczami",
        value: "Rampa wejściowa od strony ul. Karmelickiej, asysta personelu bileterskiego",
        source: "Zgłoszenie do rejestru",
        date: "2026-09-20",
        reliability: "Do sprawdzenia",
      },
    ],
    x: 44,
    y: 37,
    lat: 50.0641,
    lng: 19.9329,
    description: "Popularny teatr komediowy i dramatyczny u zbiegu ulic Karmelickiej i Podwale. Zgłoszony do ponownego audytu w celu poszerzenia certyfikacji o pętlę indukcyjną.",
    verified: false,
    verificationStatus: "oczekuje",
    submittedByOwnerName: "Dyrektor Administracyjny Teatru Bagatela",
    rating: 4.7,
    reviewsCount: 41,
    tags: ["teatr", "spektakl", "komedia", "farsa", "aktorzy", "kultura", "rozrywka"],
  },
  {
    id: "muzeum-narodowe-krakow",
    name: "Muzeum Narodowe w Krakowie (Gmach Główny)",
    category: "kultura",
    categoryLabel: "Kultura",
    address: "al. 3 Maja 1, 30-062 Kraków",
    hours: "10:00 - 18:00 (wt-nd)",
    features: [
      "Winda dostosowana do wózków",
      "Wejście bezprogowe (poziom 0)",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
      "Audiodeskrypcja (menu / przewodnik)",
      "Ścieżki dotykowe i linie naprowadzające",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Szeroka rampa zewnętrzna oraz automatyczne drzwi obrotowe z przyciskiem spowalniającym",
        source: "Oficjalny Raport Dostępności MNK",
        date: "2026-05-15",
        reliability: "Potwierdzone",
      },
      {
        label: "Winda dostosowana do wózków",
        value: "Przestronne windy z systemem komunikatów głosowych łączące wszystkie kondygnacje wystawowe",
        source: "Audyt Urzędu Miasta",
        date: "2026-05-15",
        reliability: "Potwierdzone",
      },
    ],
    x: 36,
    y: 43,
    lat: 50.0601,
    lng: 19.9234,
    description: "Główny gmach Muzeum Narodowego. Wzorcowa instytucja kultury pod względem dostępności architektonicznej i sensorycznej. Posiada tyflografiki, ścieżki dotykowe i pętle indukcyjne.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-05-15",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.8,
    reviewsCount: 52,
    tags: ["muzeum", "wystawa", "sztuka", "malarstwo", "zabytki", "kultura", "historia", "zwiedzanie", "edukacja"],
  },
  {
    id: "zamek-krolewski-wawel",
    name: "Zamek Królewski na Wawelu",
    category: "kultura",
    categoryLabel: "Kultura",
    address: "Wawel 5, 31-001 Kraków",
    hours: "09:00 - 17:00",
    features: [
      "Podjazd / rampa z poręczami",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
      "Audiodeskrypcja (menu / przewodnik)",
      "Miejsca siedzące do odpoczynku",
    ],
    accessibility: [
      {
        label: "Podjazd / rampa z poręczami",
        value: "Dojazd na Wzgórze Wawelskie od strony ul. Bernardyńskiej z łagodnym podjazdem, schodołazy i windy na wystawach Reprezentacyjnych Komnat",
        source: "Dział Edukacji i Dostępności Wawelu",
        date: "2026-07-01",
        reliability: "Potwierdzone",
      },
    ],
    x: 46,
    y: 54,
    lat: 50.0541,
    lng: 19.9354,
    description: "Zabytkowa rezydencja królów Polski. Dostęp na wzgórze zapewniony od ul. Bernardyńskiej, w wybranych komnatach zainstalowano windy i podnośniki schodowe.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-07-01",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.9,
    reviewsCount: 110,
    tags: ["zamek", "wawel", "król", "muzeum", "historia", "zabytki", "turystyka", "zwiedzanie", "kultura"],
  },
  {
    id: "kino-pod-baranami",
    name: "Kino Pod Baranami",
    category: "kultura",
    categoryLabel: "Kultura",
    address: "Rynek Główny 27, 31-010 Kraków",
    hours: "12:00 - 23:00",
    features: [
      "Winda dostosowana do wózków",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Napisy dla niesłyszących / transkrypcja",
    ],
    accessibility: [
      {
        label: "Winda dostosowana do wózków",
        value: "Winda w sieni Pałacu Pod Baranami prowadząca do sal kinowych na I i II piętrze",
        source: "Zgłoszenie właściciela",
        date: "2026-09-28",
        reliability: "Do sprawdzenia",
      },
    ],
    x: 47,
    y: 41,
    lat: 50.0614,
    lng: 19.9358,
    description: "Kultowe kino studyjne przy Rynku Głównym. Seanse z audiodeskrypcją i napisami dla osób niesłyszących, sala Czerwona wyposażona w pętlę indukcyjną.",
    verified: false,
    verificationStatus: "oczekuje",
    submittedByOwnerName: "Kierownik Kina Pod Baranami",
    rating: 4.8,
    reviewsCount: 33,
    tags: ["kino", "film", "seans", "kultura", "kino studyjne", "festiwal", "popcorn"],
  },

  // --- SPORT I REKREACJA ---
  {
    id: "park-wodny-krakow",
    name: "Park Wodny Kraków",
    category: "sport",
    categoryLabel: "Sport i Rekreacja",
    address: "ul. Dobrego Pasterza 126, 31-416 Kraków",
    hours: "08:00 - 22:00",
    features: [
      "Winda dostosowana do wózków",
      "Wejście bezprogowe (poziom 0)",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
      "Dźwig / podnośnik basenowy",
      "Szerokie ciągi komunikacyjne (min. 120 cm)",
    ],
    accessibility: [
      {
        label: "Dźwig / podnośnik basenowy",
        value: "Atestowany podnośnik hydrauliczny do wprowadzania osób z niepełnosprawnością bezpośrednio do niecki basenowej",
        source: "Certyfikacja Polskiego Związku Pływackiego",
        date: "2026-04-18",
        reliability: "Potwierdzone",
      },
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Poziom parteru, automatyczne drzwi wejściowe, bezprogowe szatnie rodzinne",
        source: "Audyt Miejski",
        date: "2026-04-18",
        reliability: "Potwierdzone",
      },
    ],
    x: 62,
    y: 22,
    lat: 50.0889,
    lng: 19.9822,
    description: "Jeden z największych krytych parków wodnych w Europie. Posiada specjalistyczne podnośniki basenowe, wózki kąpielowe, dedykowane przebieralnie oraz parking.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-04-18",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.7,
    reviewsCount: 78,
    tags: ["basen", "pływanie", "aquapark", "sport", "rekreacja", "woda", "zjeżdżalnie", "sauna", "trening"],
  },
  {
    id: "tauron-arena-krakow",
    name: "TAURON Arena Kraków",
    category: "sport",
    categoryLabel: "Sport i Rekreacja",
    address: "ul. Stanisława Lema 7, 31-571 Kraków",
    hours: "08:00 - 22:00 (zależnie od wydarzeń)",
    features: [
      "Winda dostosowana do wózków",
      "Wejście bezprogowe (poziom 0)",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Szerokie ciągi komunikacyjne (min. 120 cm)",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Wejścia dedykowane (Brama 1 i Brama 3) bez stopni, specjalne podesty na trybunach dla użytkowników wózków",
        source: "Raport Architektoniczny Areny",
        date: "2026-03-12",
        reliability: "Potwierdzone",
      },
    ],
    x: 70,
    y: 44,
    lat: 50.0681,
    lng: 19.9912,
    description: "Największa hala widowiskowo-sportowa w Polsce. W pełni przystosowana dla osób z niepełnosprawnościami: dedykowane platformy widokowe, windy, parking podziemny z bezpośrednim dostępem.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-03-12",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.9,
    reviewsCount: 95,
    tags: ["arena", "hala", "koncert", "sport", "widowisko", "mecz", "siatkówka", "koszykówka", "wydarzenie"],
  },
  {
    id: "plywalnia-korona-krakow",
    name: "Pływalnia KS Korona Kraków",
    category: "sport",
    categoryLabel: "Sport i Rekreacja",
    address: "ul. Kalwaryjska 9-15, 30-504 Kraków",
    hours: "06:00 - 22:00",
    features: [
      "Podjazd / rampa z poręczami",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
    ],
    accessibility: [
      {
        label: "Podjazd / rampa z poręczami",
        value: "Rampa przy wejściu bocznym od ul. Zamoyskiego, szerokość 130 cm",
        source: "Zgłoszenie klubu sportowego",
        date: "2026-09-10",
        reliability: "Do sprawdzenia",
      },
    ],
    x: 49,
    y: 62,
    lat: 50.0435,
    lng: 19.9451,
    description: "Historyczny basen na Podgórzu. Wdrożono rampę podjazdową oraz zmodernizowano węzeł sanitarny. Oczekuje na audyt podnośnika basenowego.",
    verified: false,
    verificationStatus: "oczekuje",
    submittedByOwnerName: "Zarząd KS Korona",
    rating: 4.4,
    reviewsCount: 26,
    tags: ["basen", "pływanie", "sport", "trening", "podgórze", "rekreacja", "tor pływacki"],
  },

  // --- ZDROWIE I URZĘDY ---
  {
    id: "urzad-miasta-krakowa-wszystkich-swietych",
    name: "Urząd Miasta Krakowa (pl. Wszystkich Świętych)",
    category: "zdrowie",
    categoryLabel: "Zdrowie i Urzędy",
    address: "pl. Wszystkich Świętych 3-4, 31-004 Kraków",
    hours: "07:30 - 15:30 (pon-pt)",
    features: [
      "Winda dostosowana do wózków",
      "Wejście bezprogowe (poziom 0)",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Toaleta przystosowana (z uchwytami)",
      "Tłumacz języka migowego (PJM)",
      "Ścieżki dotykowe i linie naprowadzające",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Wejście od dziedzińca z poziomu gruntu, automatyczne drzwi z przyciskiem przyzywowym",
        source: "Wydział Polityki Społecznej UMK",
        date: "2026-01-15",
        reliability: "Potwierdzone",
      },
      {
        label: "Tłumacz języka migowego (PJM)",
        value: "Stanowisko z obsługą tłumacza online w czasie rzeczywistym oraz tłumacz stacjonarny",
        source: "Wydział Polityki Społecznej UMK",
        date: "2026-01-15",
        reliability: "Potwierdzone",
      },
    ],
    x: 49,
    y: 45,
    lat: 50.0588,
    lng: 19.9381,
    description: "Główna siedziba Magistratu Miasta Krakowa. Budynek wyposażony w stanowisko z pętlą indukcyjną, tłumacza PJM online, tyflomapy oraz windę z komunikatami głosowymi.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-01-15",
    verifiedBy: "Główny Audytor Dostępności UMK",
    rating: 4.8,
    reviewsCount: 30,
    tags: ["urząd", "magistrat", "miasto", "dokumenty", "sprawy", "obywatel", "prezydent", "dowód osobisty", "zameldowanie"],
  },
  {
    id: "szpital-uniwersytecki-prokocim",
    name: "Szpital Uniwersytecki w Krakowie (Nowa Siedziba)",
    category: "zdrowie",
    categoryLabel: "Zdrowie i Urzędy",
    address: "ul. Jakubowskiego 2, 30-688 Kraków",
    hours: "Całodobowo (24/7)",
    features: [
      "Winda dostosowana do wózków",
      "Wejście bezprogowe (poziom 0)",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
      "Szerokie ciągi komunikacyjne (min. 120 cm)",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Ścieżki dotykowe i linie naprowadzające",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Nowoczesny kompleks medyczny zaprojektowany w 100% bez barier architektonicznych",
        source: "Dokumentacja Budowlana Szpitala",
        date: "2026-02-10",
        reliability: "Potwierdzone",
      },
    ],
    x: 75,
    y: 80,
    lat: 50.0075,
    lng: 20.0089,
    description: "Najnowocześniejszy kompleks szpitalny w Małopolsce. Pełna dostępność wszystkich klinik, oddziałów ratunkowych SOR i poradni specjalistycznych.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-02-10",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.9,
    reviewsCount: 88,
    tags: ["szpital", "lekarz", "medycyna", "zdrowie", "pomoc", "SOR", "dyżur", "poradnia", "badania", "klinika"],
  },
  {
    id: "apteka-sloneczna-karmelicka",
    name: "Apteka Słoneczna Całodobowa",
    category: "zdrowie",
    categoryLabel: "Zdrowie i Urzędy",
    address: "ul. Karmelicka 23, 31-131 Kraków",
    hours: "Całodobowo (24/7)",
    features: [
      "Podjazd / rampa z poręczami",
      "Pętla indukcyjna (strefa obsługi / sala)",
    ],
    accessibility: [
      {
        label: "Podjazd / rampa z poręczami",
        value: "Podjazd przy wejściu do dyżuru nocnego, dzwonek przyzywowy na wysokości 90 cm",
        source: "Zgłoszenie farmaceuty",
        date: "2026-09-18",
        reliability: "Do sprawdzenia",
      },
    ],
    x: 43,
    y: 34,
    lat: 50.0661,
    lng: 19.9312,
    description: "Apteka całodobowa z okienkiem nocnym. Zgłoszony podjazd i dzwonek przyzywowy dla osób na wózkach. Weryfikacja w toku.",
    verified: false,
    verificationStatus: "oczekuje",
    submittedByOwnerName: "Kierownik Apteki Słonecznej",
    rating: 4.6,
    reviewsCount: 15,
    tags: ["apteka", "leki", "recepta", "dyżur", "całodobowa", "zdrowie", "farmacja", "ból"],
  },
  {
    id: "urzad-miasta-powstania-warszawskiego",
    name: "Urząd Miasta Krakowa (al. Powstania Warszawskiego)",
    category: "zdrowie",
    categoryLabel: "Zdrowie i Urzędy",
    address: "al. Powstania Warszawskiego 10, 31-549 Kraków",
    hours: "07:40 - 18:00 (pon-pt)",
    features: [
      "Winda dostosowana do wózków",
      "Wejście bezprogowe (poziom 0)",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Toaleta przystosowana (z uchwytami)",
      "Dedykowany parking dla niepełnosprawnych",
      "Tłumacz języka migowego (PJM)",
    ],
    accessibility: [
      {
        label: "Wejście bezprogowe (poziom 0)",
        value: "Wejście główne z chodnika al. Powstania Warszawskiego z drzwiami automatycznymi, biletomaty z regulacją wysokości",
        source: "Wydział Ewidencji Pojazdów i Spraw Społecznych",
        date: "2026-04-05",
        reliability: "Potwierdzone",
      },
    ],
    x: 58,
    y: 42,
    lat: 50.0612,
    lng: 19.9575,
    description: "Centrum Obsługi Mieszkańców (rejestracja pojazdów, prawa jazdy, dowody). Przestronna sala obsługi, pętle indukcyjne na każdym stanowisku i obniżone lady.",
    verified: true,
    verificationStatus: "zatwierdzony",
    verifiedAt: "2026-04-05",
    verifiedBy: "Urząd Miasta Krakowa",
    rating: 4.7,
    reviewsCount: 45,
    tags: ["urząd", "prawo jazdy", "samochód", "rejestracja", "dokumenty", "sprawy", "miasto", "mieszkaniec"],
  },
];
