import { Place, Review, Report, UserProfile } from "./types";

export const DEMO_USERS: UserProfile[] = [
  {
    id: "user-1",
    name: "Marta Kowalska",
    email: "marta@krakow.pl",
    role: "user",
    roleLabel: "Mieszkaniec / Tester Dostępności",
    initials: "MK",
    badge: "Strażnik Dostępności",
    points: 340,
  },
  {
    id: "owner-1",
    name: "Jan Nowak",
    email: "biuro@wspolczesna.pl",
    role: "owner",
    roleLabel: "Właściciel Obiektu",
    initials: "JN",
    badge: "Zarządca Certyfikowany",
    points: 120,
    ownedPlaceIds: ["1", "4"],
  },
  {
    id: "admin-1",
    name: "Aleksandra Wiśniewska",
    email: "admin@krakow-dostepny.pl",
    role: "admin",
    roleLabel: "Administrator Miejski",
    initials: "AW",
    badge: "Oficer Dostępności Urzędu Miasta",
    points: 980,
  },
];

export const ACCESSIBILITY_CATALOG = [
  { id: "bezprogowe", label: "Wejście bezprogowe (poziom 0)", category: "Ruchowa", icon: "door-open" },
  { id: "podjazd", label: "Podjazd / rampa z poręczami", category: "Ruchowa", icon: "accessibility" },
  { id: "winda", label: "Winda dostosowana do wózków", category: "Ruchowa", icon: "arrow-up-down" },
  { id: "toaleta", label: "Toaleta przystosowana (z uchwytami)", category: "Ruchowa", icon: "bath" },
  { id: "szerokie_przejscia", label: "Szerokie ciągi komunikacyjne (min. 120 cm)", category: "Ruchowa", icon: "maximize" },
  { id: "parking", label: "Dedykowany parking dla niepełnosprawnych", category: "Ruchowa", icon: "car" },
  { id: "indukcyjna", label: "Pętla indukcyjna (strefa obsługi / sala)", category: "Słuchowa", icon: "volume-2" },
  { id: "pjm", label: "Obsługa w Polskim Języku Migowym (PJM)", category: "Słuchowa", icon: "languages" },
  { id: "napisy", label: "Napisy dla niesłyszących / transkrypcja", category: "Słuchowa", icon: "message-square" },
  { id: "audio", label: "Audiodeskrypcja (menu / przewodnik)", category: "Wzrokowa", icon: "headphones" },
  { id: "braille", label: "Oznaczenia w alfabecie Braille'a", category: "Wzrokowa", icon: "eye" },
  { id: "sciezki", label: "Ścieżki dotykowe i linie naprowadzające", category: "Wzrokowa", icon: "footprints" },
  { id: "pies", label: "Przyjazne dla psa przewodnika / asystującego", category: "Wzrokowa", icon: "heart-handshake" },
  { id: "ciche_godziny", label: "Ciche godziny / strefa wyciszenia sensorycznego", category: "Sensoryczna", icon: "volume-x" },
  { id: "miejsca_odpoczynku", label: "Miejsca siedzące do odpoczynku", category: "Ogólna", icon: "armchair" },
];

export const INITIAL_PLACES: Place[] = [
  {
    id: "1",
    name: "Restauracja Współczesna",
    category: "restauracje",
    categoryLabel: "Restauracje",
    address: "ul. Starowiślna 84, Kraków",
    hours: "08:00 - 22:00",
    phone: "+48 12 555 12 34",
    ownerId: "owner-1",
    verified: true,
    rating: 4.8,
    reviewsCount: 12,
    features: [
      "Wejście bezprogowe (poziom 0)",
      "Pętla indukcyjna w strefie obsługi",
      "Menu z audiodeskrypcją",
      "Toaleta przystosowana",
      "Przyjazne dla psa przewodnika / asystującego",
    ],
    accessibility: [
      { label: "Wejście bezprogowe", value: "Dostępne", source: "Właściciel obiektu", date: "2026-09-18", reliability: "Potwierdzone" },
      { label: "Próg przy wejściu", value: "0 cm (brak)", source: "Właściciel obiektu", date: "2026-09-18", reliability: "Potwierdzone" },
      { label: "Szerokość wejścia", value: "110 cm", source: "Właściciel obiektu", date: "2026-09-18", reliability: "Potwierdzone" },
      { label: "Toaleta dostępna", value: "Poziom 0, uchwyty, dzwonek", source: "Właściciel obiektu", date: "2026-09-18", reliability: "Potwierdzone" },
      { label: "Miejsca odpoczynku", value: "Dostępne", source: "Społeczność", date: "2026-09-20", reliability: "Potwierdzone" },
    ],
    x: 44,
    y: 38,
    lat: 50.0526,
    lng: 19.9478,
    description: "Lokal z szerokimi ciągami komunikacyjnymi, obniżoną ladą oraz cichą strefą dla osób wrażliwych na bodźce dźwiękowe.",
  },
  {
    id: "2",
    name: "Kawiarnia Literacka",
    category: "restauracje",
    categoryLabel: "Restauracje",
    address: "ul. Gołębia 22, Kraków",
    hours: "09:00 - 21:00",
    phone: "+48 12 444 88 99",
    verified: false,
    rating: 4.5,
    reviewsCount: 8,
    features: [
      "Podjazd z poręczami",
      "Obsługa przeszkolona w PJM",
      "Przyjazne dla psa przewodnika / asystującego",
    ],
    accessibility: [
      { label: "Podjazd z poręczami", value: "Kąt 6%", source: "Zgłoszenie społeczności", date: "2026-08-27", reliability: "Zgłoszone" },
      { label: "Próg przy wejściu", value: "2 cm", source: "Zgłoszenie społeczności", date: "2026-08-27", reliability: "Zgłoszone" },
      { label: "Szerokość wejścia", value: "94 cm", source: "Zgłoszenie społeczności", date: "2026-08-27", reliability: "Zgłoszone" },
      { label: "Toaleta dostępna", value: "Wymaga asysty", source: "Zgłoszenie społeczności", date: "2026-08-27", reliability: "Do sprawdzenia" },
    ],
    x: 64,
    y: 34,
    lat: 50.0614,
    lng: 19.9342,
    description: "Dostępna kawiarnia miejska z rampą najazdową i toaletą zgodną ze standardem dostępności architektonicznej.",
  },
  {
    id: "3",
    name: "Muzeum Sztuki i Historii",
    category: "kultura",
    categoryLabel: "Kultura",
    address: "ul. Piłsudskiego 3, Kraków",
    hours: "10:00 - 18:00",
    phone: "+48 12 621 10 31",
    verified: true,
    rating: 4.9,
    reviewsCount: 24,
    features: [
      "Audiodeskrypcja ekspozycji",
      "Ścieżki dotykowe i tyflografika",
      "Winda z komunikatami głosowymi",
      "Pętla indukcyjna na sali głównej",
      "Ciche godziny / strefa wyciszenia sensorycznego",
    ],
    accessibility: [
      { label: "Winda z komunikatami głosowymi", value: "Komunikaty PL/EN", source: "Audyt miejski", date: "2026-09-04", reliability: "Potwierdzone" },
      { label: "Schody przy wejściu głównym", value: "Podnośnik platformowy", source: "Audyt miejski", date: "2026-09-04", reliability: "Potwierdzone" },
      { label: "Szerokość wejścia", value: "120 cm", source: "Audyt miejski", date: "2026-09-04", reliability: "Potwierdzone" },
      { label: "Toaleta dostępna", value: "Pełne wyposażenie", source: "Audyt miejski", date: "2026-09-04", reliability: "Potwierdzone" },
      { label: "Miejsca odpoczynku", value: "Fotele na każdym piętrze", source: "Audyt miejski", date: "2026-09-04", reliability: "Potwierdzone" },
    ],
    x: 52,
    y: 50,
    lat: 50.0601,
    lng: 19.9318,
    description: "Przestrzeń wystawiennicza bez barier poziomych i pionowych, z wypożyczalnią wózków oraz dedykowanymi asystentami.",
  },
  {
    id: "4",
    name: "Teatr Miejski",
    category: "kultura",
    categoryLabel: "Kultura",
    address: "pl. Szczepański 1, Kraków",
    hours: "10:00 - 19:00",
    phone: "+48 12 656 72 00",
    ownerId: "owner-1",
    verified: true,
    rating: 4.7,
    reviewsCount: 19,
    features: [
      "Miejsca dla osób na wózkach",
      "Napisy dla niesłyszących",
      "Tłumaczenie na język migowy",
      "Pętla indukcyjna (strefa obsługi / sala)",
    ],
    accessibility: [
      { label: "Podjazd przy wejściu", value: "Płaski wjazd od dziedzińca", source: "Właściciel", date: "2026-09-11", reliability: "Potwierdzone" },
      { label: "Winda na widownię", value: "Dostępna z parteru", source: "Właściciel", date: "2026-09-11", reliability: "Potwierdzone" },
      { label: "Szerokość wejścia", value: "110 cm", source: "Właściciel", date: "2026-09-11", reliability: "Potwierdzone" },
      { label: "Toaleta dostępna", value: "Dostępna", source: "Właściciel", date: "2026-09-11", reliability: "Potwierdzone" },
    ],
    x: 36,
    y: 45,
    lat: 50.0638,
    lng: 19.9355,
    description: "Wybrane spektakle z audiodeskrypcją, bezpośredni bezbarierowy dostęp z poziomu parkingu podziemnego.",
  },
  {
    id: "5",
    name: "Miejski Ośrodek Sportu",
    category: "sport",
    categoryLabel: "Sport i Rekreacja",
    address: "ul. Reymonta 26, Kraków",
    hours: "06:30 - 22:00",
    phone: "+48 12 825 40 10",
    verified: true,
    rating: 4.8,
    reviewsCount: 15,
    features: [
      "Podnośnik basenowy",
      "Dostosowane szatnie i prysznice",
      "Wejście bezprogowe (poziom 0)",
      "Dedykowany parking dla niepełnosprawnych",
    ],
    accessibility: [
      { label: "Podjazd przy wejściu", value: "Bezstopniowy wjazd", source: "Właściciel obiektu", date: "2026-07-15", reliability: "Potwierdzone" },
      { label: "Brak progów", value: "Cały parter", source: "Właściciel obiektu", date: "2026-07-15", reliability: "Potwierdzone" },
      { label: "Winda na trybuny", value: "Szerokość 110 cm", source: "Właściciel obiektu", date: "2026-07-15", reliability: "Potwierdzone" },
      { label: "Miejsca odpoczynku", value: "Przy każdej sali", source: "Właściciel obiektu", date: "2026-07-15", reliability: "Potwierdzone" },
    ],
    x: 66,
    y: 65,
    lat: 50.0645,
    lng: 19.9142,
    description: "Kompleks sportowy z certyfikowaną infrastrukturą przystosowaną do treningu osób z ograniczoną sprawnością ruchową.",
  },
  {
    id: "6",
    name: "Centrum Zdrowia i Obsługi Mieszkańców",
    category: "zdrowie",
    categoryLabel: "Zdrowie i Urzędy",
    address: "ul. Długa 14, Kraków",
    hours: "07:30 - 18:00",
    phone: "+48 12 616 55 55",
    verified: true,
    rating: 4.9,
    reviewsCount: 31,
    features: [
      "Automatycznie otwierane drzwi",
      "Obniżone stanowisko obsługi klienta",
      "System kolejkowy z komunikatami głosowymi",
      "Pętla indukcyjna (strefa obsługi / sala)",
      "Obsługa w Polskim Języku Migowym (PJM)",
    ],
    accessibility: [
      { label: "Drzwi automatyczne", value: "Szerokość 140 cm", source: "Wydział Polityki Społecznej", date: "2026-09-22", reliability: "Potwierdzone" },
      { label: "Lada recepcyjna", value: "Wysokość 75 cm", source: "Wydział Polityki Społecznej", date: "2026-09-22", reliability: "Potwierdzone" },
      { label: "Winda z systemem Braille'a", value: "Głosowe zapowiedzi pięter", source: "Wydział Polityki Społecznej", date: "2026-09-22", reliability: "Potwierdzone" },
      { label: "Toaleta przystosowana", value: "Dostępna na każdym piętrze", source: "Wydział Polityki Społecznej", date: "2026-09-22", reliability: "Potwierdzone" },
    ],
    x: 48,
    y: 22,
    lat: 50.0682,
    lng: 19.9372,
    description: "Referencyjny punkt obsługi mieszkańców przygotowany zgodnie z ustawą o zapewnianiu dostępności osobom ze szczególnymi potrzebami.",
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    placeId: "1",
    author: "Marta K.",
    initials: "MK",
    role: "Mieszkaniec",
    userId: "user-1",
    place: "Restauracja Współczesna",
    text: "Szerokie przejście i bardzo pomocna obsługa. Pętla indukcyjna działa bez zarzutu, a stoliki mają wygodną wysokość dla osoby poruszającej się na wózku.",
    date: "2 godz. temu",
    rating: 5,
    accent: "bg-cyan-100 text-cyan-800",
    verifiedFeatures: ["Wejście bezprogowe (poziom 0)", "Pętla indukcyjna w strefie obsługi", "Toaleta przystosowana"],
    ownerReply: {
      author: "Jan Nowak (Właściciel)",
      text: "Pani Marto, serdecznie dziękujemy za wizytę! Cieszymy się, że pętla indukcyjna i stoliki spełniły oczekiwania.",
      date: "1 godz. temu",
    },
  },
  {
    id: "rev-2",
    placeId: "4",
    author: "Teatr Miejski",
    initials: "TM",
    role: "Właściciel",
    place: "Teatr Miejski",
    text: "Dodaliśmy napisy do sobotniego spektaklu. Zaktualizowaliśmy też oznaczenia miejsc dla wózków na parterze.",
    date: "wczoraj",
    rating: 5,
    accent: "bg-blue-100 text-blue-800",
  },
  {
    id: "rev-3",
    placeId: "3",
    author: "Tomek P.",
    initials: "TP",
    role: "Mieszkaniec",
    place: "Muzeum Sztuki i Historii",
    text: "Dobra trasa od wejścia do windy, dużo spokoju i czytelne oznaczenia. Audiodeskrypcja dostępna po wcześniejszej rezerwacji w kasie biletowej.",
    date: "3 dni temu",
    rating: 4,
    accent: "bg-amber-100 text-amber-800",
    verifiedFeatures: ["Audiodeskrypcja ekspozycji", "Winda z komunikatami głosowymi"],
  },
];

export const INITIAL_REPORTS: Report[] = [
  {
    id: "rep-1",
    userId: "user-1",
    userName: "Marta Kowalska",
    placeId: "2",
    placeName: "Kawiarnia Literacka",
    category: "Rampy i wejścia",
    title: "Zbyt stromy kąt podjazdu bocznego",
    description: "Rampa przy wejściu od podwórza ma kąt nachylenia ok. 12%, co bez asysty uniemożliwia wjazd wózkiem mechanicznym.",
    status: "Oczekujące",
    createdAt: "2026-10-02 14:30",
    updatedAt: "2026-10-02 14:30",
  },
  {
    id: "rep-2",
    userId: "user-1",
    userName: "Marta Kowalska",
    placeId: "1",
    placeName: "Restauracja Współczesna",
    category: "Weryfikacja udogodnień",
    title: "Potwierdzenie nowej pętli indukcyjnej",
    description: "Sprawdziłam osobiście działanie nowej pętli przy kasie restauracji - działa czysto bez szumów.",
    status: "Potwierdzone",
    createdAt: "2026-09-28 11:15",
    updatedAt: "2026-09-29 09:00",
    notes: "Zweryfikowano przez inspektora miejskiego podczas audytu.",
  },
  {
    id: "rep-3",
    userId: "user-2",
    userName: "Piotr Zieliński",
    placeId: "4",
    placeName: "Teatr Miejski",
    category: "Napisy i tłumaczenia",
    title: "Brak tłumacza PJM na spektaklu niedzielnym",
    description: "Mimo oznaczenia w repertuarze tłumacz nie pojawił się w wyznaczonym sektorze.",
    status: "W realizacji",
    createdAt: "2026-10-01 19:40",
    updatedAt: "2026-10-02 10:20",
    notes: "Teatr wyjaśnia sytuację z agencją tłumaczy.",
  },
];
